rootProject.name = "OneRepMaxTracker"
include(":app")
include(":core-base")
include(":persistence")
include(":libraries:oneRepMax")
include(":features:greatest1RM")
include(":persistence:database-room")
include(":persistence:asset")
include(":core-base:ui")
include(":features:detailGreatest1RM")
include(":core-base:domain-data-layer")
include(":core-base:context")
include(":core-base:navigation")
include(":core-base:test")
