object Versions {
    const val androidGradle = "7.0.4"
    const val kotlin = "1.5.20"
    const val kapt = "1.6.10"
    const val coroutines = "1.3.9"
    const val fragment = "1.4.0"
    const val viewModelScope = "2.2.0"
    const val appCompat = "1.3.0"
    const val coreKtx = "1.3.2"
    const val koin = "3.1.5"
    const val room = "2.4.1"
    const val material = "1.3.0"
    const val constraintLayout = "2.0.4"
    const val mpaAndroidChart = "3.1.0"
    const val desugar = "1.1.5"

    const val jUnit = "4.12"
    const val coroutinesTest = "1.6.0"
    const val mockitoKotlin = "4.0.0"
    const val mockitoInline = "4.1.0"
    const val kluent = "1.68"
    const val arch = "2.1.0"
}